// packages/solid-leva/src/components/Folder/FolderTitle.tsx
import { title } from "./styles";
import { Chevron } from "../UI";
import { JSX } from "solid-js";
export type FolderTitleProps = {
  name?: string;
  toggled: boolean;
  toggle: (flag?: boolean) => void;
};

export function FolderTitle(props: FolderTitleProps) {
  return (
    <div class={title()} onClick={() => props.toggle()}>
      <Chevron toggled={props.toggled} />
      <div>{props.name}</div>
    </div>
  );
}

// apps/chess/src/lib/leva-spline/FolderTitle.tsx
import * as React from "solid-react-compat";
import { Chevron } from "./Chevron";
import { StyledTitle } from "./StyledFolder";

export type FolderTitleProps = {
  name?: string;
  toggled: boolean;
  toggle: (flag?: boolean) => void;
};

export function FolderTitle({ toggle, toggled, name }: FolderTitleProps) {
  return (
    <StyledTitle onClick={() => toggle()}>
      <Chevron toggled={toggled} />
      <div>{name}</div>
    </StyledTitle>
  );
}
